mprovement and enhancement
FusixGit/WiFiPasswordSearcher pull request #12
Opened 2018-04-28 16:16 UTC by RUSHCOW0

2018-04-28 16:31 UTC, binarymaster requested changes
Пожалуйста исправьте проблемы, озвученные выше.

Спасибо заранее!

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +
Лишние строки.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +			{response2 = "unkown vendor";}
Перезапись предыдущего текста с ошибкой.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +			TextView VendorWpsText = (TextView) findViewById(R.id.VendorWpsTextView);
Перезапись предыдущего кода с корректным форматированием.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +			{e.printStackTrace();}
Перезапись предыдущего кода с корректным форматированием.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +			HttpGet http = new HttpGet("http://3wifi.stascorp.com/api/apiwps?key=" + API_READ_KEY + "&bssid=" + BSSID);
Перезапись предыдущего корректного кода.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +			ResponseHandler res2 = new BasicResponseHandler();
Это ломает сборку в Android Studio.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +			pd = ProgressDialog.show(WPSActivity.this, "Waiting...", "getting pins...");
Перезапись предыдущего текста.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/WPSActivity.java
> +		ESSDWpsText.setText(ESSDWps); // ESSD
Перезапись предыдущего кода.

2018-04-28 16:31 UTC, binarymaster commented on app/src/main/java/com/example/WiFiPasswordSearcher/StartActivity.java
> +	}
Залогинившись один раз в локаторе, повторно вводить данные не потребуется, и приложение сможет работать автономно (в тех местах, где оно может это делать).

Всё-таки я считаю, что нет необходимости добавлять такую фичу.

2018-04-29 23:04 UTC, binarymaster approved these changes

2018-04-29 23:09 UTC, merged

2020-09-24 12:07 UTC, Heresh83 approved these changes